language: node_js
node_js:
- '4.0'
script:
- echo "Deploying!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --token "$FIREBASE_TOKEN"
env:
  secure: eentYxajf8YFeTtjdQzRIQeI4EpcUqsjBBxX3wCqEXTD/uPNAcdnvBng4tvwDYQ/oyoWrro3J8fdE8unX7FnzBKr7N61BnbL2pxGgGSdDlFn8TAVeR53rPa3HL9HbJuKHv3oWuqOguDMkjQh3dXO062QMHS3evjuFCkmrzRxBE9EABBASpJF+6aN0mlnE92ZhtVFnoyyp0ugb60ma+QiDJqa9oTNnG7NzXdqbjRV3CYuObVGmWUR6d0l1sIImHOKoI8RU2AYwXWcfBaiH7QQxVy47yXQQs+1YHE1G2xtc4gEs3rEI8/pKAq9IU+2FaKldvPNEeHk5+ucn4dGhbwMdS+QZjGWrswHidJaeXHr+roc3HozM/4HbozhgwFXZW5E2zckuKj691a4SXWRZm73xMdX19tLK9QVl/ALt1OqoMzU/X+WUm9XXfnB8yPHKGZ3mX7H94wZhS7QsL6JEZhOGQyPXiHwo3M3LmxSCJ0/jSgwDE1nhCC4HA69FuzzI10MFo+KnHgj0N5EpC9YTjMjGN/ZcqeFvLZI/TzZ6ft0Kbxi1lgUWEf4m3bm+VhOYm7H5VStLlsf5xnjYKog2Pi1tlhA3EEKuTyBQzmMfIrHqQf/woxl9iPq8vRkrFFTuiUBAkQbLPxxhFBEDJESZBFIV4sxDEWqnRR0vrg2ad89VrM=
